### PR TITLE
Feature/sim 1231/create snr module

### PR DESCRIPTION
**Pull request by danielsf**
pull request to bring sims_catUtils into sync with the new SNR API implemented in sims_photUtils

### CODE REVIEW

**Comment by danielsf** [comment]
I just merged a branch that splits the GalSim interface code off into its own repo.  This will

a) force me to do some rebasing on this pull request, so don't bother reviewing it until I say that's done

b) create another pull request on this branch in sims_GalSimInterface (the new repo).  I'll send that your way.

**Comment by rhiannonlynne** [comment]
I should still look at the sims_photUtils branch, right?

**Comment by danielsf** [comment]
Yes.  sims_photUtils is unaffected.

also: rebase is done.   Review away.

**Comment by rhiannonlynne** [comment]
Looks good.

**Pull request merged**
